# -*- coding: utf-8 -*-
"""diabetes_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ASycm8V5HLXYsrx3zmKxrlSTnxdxRZ3Z
"""

# Load directly from URL
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"

# Define column names (they're not included in the raw file)
columns = [
    "Pregnancies", "Glucose", "BloodPressure", "SkinThickness", "Insulin",
    "BMI", "DiabetesPedigreeFunction", "Age", "Outcome"
]

# Load the dataset
import pandas as pd
df = pd.read_csv(url, names=columns)

# Show first 5 rows
df.head()

# Check basic info
df.info()

# Check for missing values
print("\nMissing values:\n", df.isnull().sum())

# Statistical summary
df.describe()

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm')
plt.title("Feature Correlation Heatmap")
plt.show()

# Split into features and labels
X = df.drop("Outcome", axis=1)
y = df["Outcome"]

# Train-test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("✅ Accuracy:", accuracy_score(y_test, y_pred))
print("\n📊 Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\n📄 Classification Report:\n", classification_report(y_test, y_pred))

# 📉 ROC Curve and AUC
from sklearn.metrics import roc_curve, roc_auc_score

# Predict probabilities
y_probs = model.predict_proba(X_test_scaled)[:, 1]

# Get false positive rate, true positive rate, threshold
fpr, tpr, thresholds = roc_curve(y_test, y_probs)

# Plot ROC
plt.figure(figsize=(8,6))
plt.plot(fpr, tpr, color='darkorange', label=f'ROC curve (AUC = {roc_auc_score(y_test, y_probs):.2f})')
plt.plot([0, 1], [0, 1], color='navy', linestyle='--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend()
plt.grid()
plt.show()

from sklearn.metrics import ConfusionMatrixDisplay

cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot(cmap='Blues')
plt.title("Confusion Matrix")
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %%writefile diabetes_app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# from sklearn.linear_model import LogisticRegression
# 
# # Load dataset
# @st.cache_data
# def load_data():
#     url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
#     columns = ["Pregnancies", "Glucose", "BloodPressure", "SkinThickness", "Insulin",
#                "BMI", "DiabetesPedigreeFunction", "Age", "Outcome"]
#     return pd.read_csv(url, names=columns)
# 
# df = load_data()
# 
# X = df.drop("Outcome", axis=1)
# y = df["Outcome"]
# model = LogisticRegression(max_iter=1000)
# model.fit(X, y)
# 
# st.title("🩺 Diabetes Prediction App")
# st.write("Enter your health details below:")
# 
# pregnancies = st.number_input("Pregnancies", 0, 20, 1)
# glucose = st.number_input("Glucose", 0, 200, 110)
# blood_pressure = st.number_input("Blood Pressure", 0, 150, 70)
# skin_thickness = st.number_input("Skin Thickness", 0, 100, 20)
# insulin = st.number_input("Insulin", 0, 900, 80)
# bmi = st.number_input("BMI", 0.0, 70.0, 25.0)
# dpf = st.number_input("Diabetes Pedigree Function", 0.0, 3.0, 0.5)
# age = st.number_input("Age", 1, 100, 33)
# 
# input_data = np.array([[pregnancies, glucose, blood_pressure, skin_thickness, insulin, bmi, dpf, age]])
# 
# if st.button("Predict"):
#     prediction = model.predict(input_data)[0]
#     if prediction == 1:
#         st.error("⚠️ You may have diabetes. Please consult a doctor.")
#     else:
#         st.success("✅ You are not likely to have diabetes.")
#

# pip install streamlit pyngrok

# diabetes_app.py

import streamlit as st
import pandas as pd
import numpy as np
import pickle

st.title("Diabetes Prediction App")

st.write("Enter patient details below:")

pregnancies = st.number_input("Pregnancies", min_value=0, step=1)
glucose = st.number_input("Glucose", min_value=0)
blood_pressure = st.number_input("Blood Pressure", min_value=0)
skin_thickness = st.number_input("Skin Thickness", min_value=0)
insulin = st.number_input("Insulin", min_value=0)
bmi = st.number_input("BMI", min_value=0.0)
dpf = st.number_input("Diabetes Pedigree Function", min_value=0.0)
age = st.number_input("Age", min_value=0, step=1)

# Load model
model = pickle.load(open("diabetes_model.pkl", "rb"))

if st.button("Predict"):
    input_data = np.array([[pregnancies, glucose, blood_pressure, skin_thickness,
                            insulin, bmi, dpf, age]])
    prediction = model.predict(input_data)

    if prediction[0] == 1:
        st.error("The person is likely to have diabetes.")
    else:
        st.success("The person is unlikely to have diabetes.")

import pickle
pickle.dump(model, open("diabetes_model.pkl", "wb"))

import os

file_path = "diabetes_model.pkl"
if os.path.exists(file_path):
    print(f"File '{file_path}' is saved locally. You can find it in your project folder.")
else:
    print(f"File '{file_path}' not found.")

